name: typ_query
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
#   path: ^1.8.0
  grpc: ^3.2.4
  protobuf: ^3.1.0
  typ_p:
    path: ../../../mippo/typ-p/dart/

# dart pub get
# dart pub upgrade --major-versions
dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8
