// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: typ_query/keyword.proto

package typ_query

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Keyword struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to ValueOf:
	//
	//	*Keyword_Kv
	//	*Keyword_Keywords
	ValueOf isKeyword_ValueOf `protobuf_oneof:"value_of"`
}

func (x *Keyword) Reset() {
	*x = Keyword{}
	if protoimpl.UnsafeEnabled {
		mi := &file_typ_query_keyword_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Keyword) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Keyword) ProtoMessage() {}

func (x *Keyword) ProtoReflect() protoreflect.Message {
	mi := &file_typ_query_keyword_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Keyword.ProtoReflect.Descriptor instead.
func (*Keyword) Descriptor() ([]byte, []int) {
	return file_typ_query_keyword_proto_rawDescGZIP(), []int{0}
}

func (m *Keyword) GetValueOf() isKeyword_ValueOf {
	if m != nil {
		return m.ValueOf
	}
	return nil
}

func (x *Keyword) GetKv() *Kv {
	if x, ok := x.GetValueOf().(*Keyword_Kv); ok {
		return x.Kv
	}
	return nil
}

func (x *Keyword) GetKeywords() *Keywords {
	if x, ok := x.GetValueOf().(*Keyword_Keywords); ok {
		return x.Keywords
	}
	return nil
}

type isKeyword_ValueOf interface {
	isKeyword_ValueOf()
}

type Keyword_Kv struct {
	Kv *Kv `protobuf:"bytes,1,opt,name=kv,proto3,oneof"`
}

type Keyword_Keywords struct {
	Keywords *Keywords `protobuf:"bytes,2,opt,name=keywords,proto3,oneof"`
}

func (*Keyword_Kv) isKeyword_ValueOf() {}

func (*Keyword_Keywords) isKeyword_ValueOf() {}

type Keywords struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Operant  string     `protobuf:"bytes,1,opt,name=operant,proto3" json:"operant,omitempty"`
	Keywords []*Keyword `protobuf:"bytes,2,rep,name=keywords,proto3" json:"keywords,omitempty"`
}

func (x *Keywords) Reset() {
	*x = Keywords{}
	if protoimpl.UnsafeEnabled {
		mi := &file_typ_query_keyword_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Keywords) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Keywords) ProtoMessage() {}

func (x *Keywords) ProtoReflect() protoreflect.Message {
	mi := &file_typ_query_keyword_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Keywords.ProtoReflect.Descriptor instead.
func (*Keywords) Descriptor() ([]byte, []int) {
	return file_typ_query_keyword_proto_rawDescGZIP(), []int{1}
}

func (x *Keywords) GetOperant() string {
	if x != nil {
		return x.Operant
	}
	return ""
}

func (x *Keywords) GetKeywords() []*Keyword {
	if x != nil {
		return x.Keywords
	}
	return nil
}

var File_typ_query_keyword_proto protoreflect.FileDescriptor

var file_typ_query_keyword_proto_rawDesc = []byte{
	0x0a, 0x17, 0x74, 0x79, 0x70, 0x5f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2f, 0x6b, 0x65, 0x79, 0x77,
	0x6f, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x74, 0x79, 0x70, 0x5f, 0x71,
	0x75, 0x65, 0x72, 0x79, 0x1a, 0x12, 0x74, 0x79, 0x70, 0x5f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2f,
	0x6b, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x69, 0x0a, 0x07, 0x4b, 0x65, 0x79, 0x77,
	0x6f, 0x72, 0x64, 0x12, 0x1f, 0x0a, 0x02, 0x6b, 0x76, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x74, 0x79, 0x70, 0x5f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x4b, 0x76, 0x48, 0x00,
	0x52, 0x02, 0x6b, 0x76, 0x12, 0x31, 0x0a, 0x08, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x74, 0x79, 0x70, 0x5f, 0x71, 0x75, 0x65,
	0x72, 0x79, 0x2e, 0x4b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x48, 0x00, 0x52, 0x08, 0x6b,
	0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x42, 0x0a, 0x0a, 0x08, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x5f, 0x6f, 0x66, 0x22, 0x54, 0x0a, 0x08, 0x4b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x6e, 0x74, 0x12, 0x2e, 0x0a, 0x08, 0x6b, 0x65, 0x79,
	0x77, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x74, 0x79,
	0x70, 0x5f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x4b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x52,
	0x08, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74,
	0x6c, 0x61, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x69, 0x70, 0x70, 0x6f, 0x2e, 0x61, 0x70,
	0x70, 0x2f, 0x74, 0x79, 0x70, 0x2d, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x67, 0x69, 0x74, 0x2f,
	0x67, 0x6f, 0x2f, 0x70, 0x62, 0x2f, 0x74, 0x79, 0x70, 0x5f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_typ_query_keyword_proto_rawDescOnce sync.Once
	file_typ_query_keyword_proto_rawDescData = file_typ_query_keyword_proto_rawDesc
)

func file_typ_query_keyword_proto_rawDescGZIP() []byte {
	file_typ_query_keyword_proto_rawDescOnce.Do(func() {
		file_typ_query_keyword_proto_rawDescData = protoimpl.X.CompressGZIP(file_typ_query_keyword_proto_rawDescData)
	})
	return file_typ_query_keyword_proto_rawDescData
}

var file_typ_query_keyword_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_typ_query_keyword_proto_goTypes = []any{
	(*Keyword)(nil),  // 0: typ_query.Keyword
	(*Keywords)(nil), // 1: typ_query.Keywords
	(*Kv)(nil),       // 2: typ_query.Kv
}
var file_typ_query_keyword_proto_depIdxs = []int32{
	2, // 0: typ_query.Keyword.kv:type_name -> typ_query.Kv
	1, // 1: typ_query.Keyword.keywords:type_name -> typ_query.Keywords
	0, // 2: typ_query.Keywords.keywords:type_name -> typ_query.Keyword
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_typ_query_keyword_proto_init() }
func file_typ_query_keyword_proto_init() {
	if File_typ_query_keyword_proto != nil {
		return
	}
	file_typ_query_kv_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_typ_query_keyword_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Keyword); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_typ_query_keyword_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Keywords); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_typ_query_keyword_proto_msgTypes[0].OneofWrappers = []any{
		(*Keyword_Kv)(nil),
		(*Keyword_Keywords)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_typ_query_keyword_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_typ_query_keyword_proto_goTypes,
		DependencyIndexes: file_typ_query_keyword_proto_depIdxs,
		MessageInfos:      file_typ_query_keyword_proto_msgTypes,
	}.Build()
	File_typ_query_keyword_proto = out.File
	file_typ_query_keyword_proto_rawDesc = nil
	file_typ_query_keyword_proto_goTypes = nil
	file_typ_query_keyword_proto_depIdxs = nil
}
