// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: typ_query/kv.proto

package typ_query

import (
	typ_p "gitlab.com/mippo.app/typ-p.git/go/pb/typ_p"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KvOp int32

const (
	KvOp_KV_OP_UNKNOWN KvOp = 0
	KvOp_KV_OP_EQ      KvOp = 1
)

// Enum value maps for KvOp.
var (
	KvOp_name = map[int32]string{
		0: "KV_OP_UNKNOWN",
		1: "KV_OP_EQ",
	}
	KvOp_value = map[string]int32{
		"KV_OP_UNKNOWN": 0,
		"KV_OP_EQ":      1,
	}
)

func (x KvOp) Enum() *KvOp {
	p := new(KvOp)
	*p = x
	return p
}

func (x KvOp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KvOp) Descriptor() protoreflect.EnumDescriptor {
	return file_typ_query_kv_proto_enumTypes[0].Descriptor()
}

func (KvOp) Type() protoreflect.EnumType {
	return &file_typ_query_kv_proto_enumTypes[0]
}

func (x KvOp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KvOp.Descriptor instead.
func (KvOp) EnumDescriptor() ([]byte, []int) {
	return file_typ_query_kv_proto_rawDescGZIP(), []int{0}
}

type Kv struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key     string       `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Operant string       `protobuf:"bytes,3,opt,name=operant,proto3" json:"operant,omitempty"`
	Value   *typ_p.Value `protobuf:"bytes,20,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Kv) Reset() {
	*x = Kv{}
	if protoimpl.UnsafeEnabled {
		mi := &file_typ_query_kv_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Kv) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kv) ProtoMessage() {}

func (x *Kv) ProtoReflect() protoreflect.Message {
	mi := &file_typ_query_kv_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kv.ProtoReflect.Descriptor instead.
func (*Kv) Descriptor() ([]byte, []int) {
	return file_typ_query_kv_proto_rawDescGZIP(), []int{0}
}

func (x *Kv) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Kv) GetOperant() string {
	if x != nil {
		return x.Operant
	}
	return ""
}

func (x *Kv) GetValue() *typ_p.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_typ_query_kv_proto protoreflect.FileDescriptor

var file_typ_query_kv_proto_rawDesc = []byte{
	0x0a, 0x12, 0x74, 0x79, 0x70, 0x5f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2f, 0x6b, 0x76, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x74, 0x79, 0x70, 0x5f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x1a,
	0x11, 0x74, 0x79, 0x70, 0x5f, 0x70, 0x2f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x54, 0x0a, 0x02, 0x4b, 0x76, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x70,
	0x65, 0x72, 0x61, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x70, 0x65,
	0x72, 0x61, 0x6e, 0x74, 0x12, 0x22, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x14, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x74, 0x79, 0x70, 0x5f, 0x70, 0x2e, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x2a, 0x27, 0x0a, 0x04, 0x4b, 0x76, 0x4f, 0x70,
	0x12, 0x11, 0x0a, 0x0d, 0x4b, 0x56, 0x5f, 0x4f, 0x50, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57,
	0x4e, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x4b, 0x56, 0x5f, 0x4f, 0x50, 0x5f, 0x45, 0x51, 0x10,
	0x01, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x6d, 0x69, 0x70, 0x70, 0x6f, 0x2e, 0x61, 0x70, 0x70, 0x2f, 0x74, 0x79, 0x70, 0x2d, 0x71, 0x75,
	0x65, 0x72, 0x79, 0x2e, 0x67, 0x69, 0x74, 0x2f, 0x67, 0x6f, 0x2f, 0x70, 0x62, 0x2f, 0x74, 0x79,
	0x70, 0x5f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_typ_query_kv_proto_rawDescOnce sync.Once
	file_typ_query_kv_proto_rawDescData = file_typ_query_kv_proto_rawDesc
)

func file_typ_query_kv_proto_rawDescGZIP() []byte {
	file_typ_query_kv_proto_rawDescOnce.Do(func() {
		file_typ_query_kv_proto_rawDescData = protoimpl.X.CompressGZIP(file_typ_query_kv_proto_rawDescData)
	})
	return file_typ_query_kv_proto_rawDescData
}

var file_typ_query_kv_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_typ_query_kv_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_typ_query_kv_proto_goTypes = []interface{}{
	(KvOp)(0),           // 0: typ_query.KvOp
	(*Kv)(nil),          // 1: typ_query.Kv
	(*typ_p.Value)(nil), // 2: typ_p.value
}
var file_typ_query_kv_proto_depIdxs = []int32{
	2, // 0: typ_query.Kv.value:type_name -> typ_p.value
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_typ_query_kv_proto_init() }
func file_typ_query_kv_proto_init() {
	if File_typ_query_kv_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_typ_query_kv_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Kv); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_typ_query_kv_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_typ_query_kv_proto_goTypes,
		DependencyIndexes: file_typ_query_kv_proto_depIdxs,
		EnumInfos:         file_typ_query_kv_proto_enumTypes,
		MessageInfos:      file_typ_query_kv_proto_msgTypes,
	}.Build()
	File_typ_query_kv_proto = out.File
	file_typ_query_kv_proto_rawDesc = nil
	file_typ_query_kv_proto_goTypes = nil
	file_typ_query_kv_proto_depIdxs = nil
}
