// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: typ_query/query.proto

package typ_query

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Query struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SearchType string `protobuf:"bytes,1,opt,name=search_type,json=searchType,proto3" json:"search_type,omitempty"`
	TargetType string `protobuf:"bytes,2,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	// Types that are assignable to ValueOf:
	//
	//	*Query_Keyword
	//	*Query_Queries
	ValueOf isQuery_ValueOf `protobuf_oneof:"value_of"`
	Levels  []*Leveler      `protobuf:"bytes,5,rep,name=levels,proto3" json:"levels,omitempty"`
}

func (x *Query) Reset() {
	*x = Query{}
	if protoimpl.UnsafeEnabled {
		mi := &file_typ_query_query_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query) ProtoMessage() {}

func (x *Query) ProtoReflect() protoreflect.Message {
	mi := &file_typ_query_query_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query.ProtoReflect.Descriptor instead.
func (*Query) Descriptor() ([]byte, []int) {
	return file_typ_query_query_proto_rawDescGZIP(), []int{0}
}

func (x *Query) GetSearchType() string {
	if x != nil {
		return x.SearchType
	}
	return ""
}

func (x *Query) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (m *Query) GetValueOf() isQuery_ValueOf {
	if m != nil {
		return m.ValueOf
	}
	return nil
}

func (x *Query) GetKeyword() *Keyword {
	if x, ok := x.GetValueOf().(*Query_Keyword); ok {
		return x.Keyword
	}
	return nil
}

func (x *Query) GetQueries() *Queries {
	if x, ok := x.GetValueOf().(*Query_Queries); ok {
		return x.Queries
	}
	return nil
}

func (x *Query) GetLevels() []*Leveler {
	if x != nil {
		return x.Levels
	}
	return nil
}

type isQuery_ValueOf interface {
	isQuery_ValueOf()
}

type Query_Keyword struct {
	Keyword *Keyword `protobuf:"bytes,3,opt,name=keyword,proto3,oneof"`
}

type Query_Queries struct {
	Queries *Queries `protobuf:"bytes,4,opt,name=queries,proto3,oneof"`
}

func (*Query_Keyword) isQuery_ValueOf() {}

func (*Query_Queries) isQuery_ValueOf() {}

type Queries struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Operant string   `protobuf:"bytes,1,opt,name=operant,proto3" json:"operant,omitempty"`
	Queries []*Query `protobuf:"bytes,2,rep,name=queries,proto3" json:"queries,omitempty"`
}

func (x *Queries) Reset() {
	*x = Queries{}
	if protoimpl.UnsafeEnabled {
		mi := &file_typ_query_query_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Queries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Queries) ProtoMessage() {}

func (x *Queries) ProtoReflect() protoreflect.Message {
	mi := &file_typ_query_query_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Queries.ProtoReflect.Descriptor instead.
func (*Queries) Descriptor() ([]byte, []int) {
	return file_typ_query_query_proto_rawDescGZIP(), []int{1}
}

func (x *Queries) GetOperant() string {
	if x != nil {
		return x.Operant
	}
	return ""
}

func (x *Queries) GetQueries() []*Query {
	if x != nil {
		return x.Queries
	}
	return nil
}

var File_typ_query_query_proto protoreflect.FileDescriptor

var file_typ_query_query_proto_rawDesc = []byte{
	0x0a, 0x15, 0x74, 0x79, 0x70, 0x5f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2f, 0x71, 0x75, 0x65, 0x72,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x74, 0x79, 0x70, 0x5f, 0x71, 0x75, 0x65,
	0x72, 0x79, 0x1a, 0x17, 0x74, 0x79, 0x70, 0x5f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2f, 0x6c, 0x65,
	0x76, 0x65, 0x6c, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x74, 0x79, 0x70,
	0x5f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2f, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe1, 0x01, 0x0a, 0x05, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x1f,
	0x0a, 0x0b, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x1f, 0x0a, 0x0b, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x2e, 0x0a, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x74, 0x79, 0x70, 0x5f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x4b, 0x65,
	0x79, 0x77, 0x6f, 0x72, 0x64, 0x48, 0x00, 0x52, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64,
	0x12, 0x2e, 0x0a, 0x07, 0x71, 0x75, 0x65, 0x72, 0x69, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x74, 0x79, 0x70, 0x5f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x51, 0x75,
	0x65, 0x72, 0x69, 0x65, 0x73, 0x48, 0x00, 0x52, 0x07, 0x71, 0x75, 0x65, 0x72, 0x69, 0x65, 0x73,
	0x12, 0x2a, 0x0a, 0x06, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x74, 0x79, 0x70, 0x5f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x4c, 0x65, 0x76,
	0x65, 0x6c, 0x65, 0x72, 0x52, 0x06, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x73, 0x42, 0x0a, 0x0a, 0x08,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x5f, 0x6f, 0x66, 0x22, 0x4f, 0x0a, 0x07, 0x51, 0x75, 0x65, 0x72,
	0x69, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x6e, 0x74, 0x12, 0x2a, 0x0a,
	0x07, 0x71, 0x75, 0x65, 0x72, 0x69, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x74, 0x79, 0x70, 0x5f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x52, 0x07, 0x71, 0x75, 0x65, 0x72, 0x69, 0x65, 0x73, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74,
	0x6c, 0x61, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x69, 0x70, 0x70, 0x6f, 0x2e, 0x61, 0x70,
	0x70, 0x2f, 0x74, 0x79, 0x70, 0x2d, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x67, 0x69, 0x74, 0x2f,
	0x67, 0x6f, 0x2f, 0x70, 0x62, 0x2f, 0x74, 0x79, 0x70, 0x5f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_typ_query_query_proto_rawDescOnce sync.Once
	file_typ_query_query_proto_rawDescData = file_typ_query_query_proto_rawDesc
)

func file_typ_query_query_proto_rawDescGZIP() []byte {
	file_typ_query_query_proto_rawDescOnce.Do(func() {
		file_typ_query_query_proto_rawDescData = protoimpl.X.CompressGZIP(file_typ_query_query_proto_rawDescData)
	})
	return file_typ_query_query_proto_rawDescData
}

var file_typ_query_query_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_typ_query_query_proto_goTypes = []interface{}{
	(*Query)(nil),   // 0: typ_query.Query
	(*Queries)(nil), // 1: typ_query.Queries
	(*Keyword)(nil), // 2: typ_query.Keyword
	(*Leveler)(nil), // 3: typ_query.Leveler
}
var file_typ_query_query_proto_depIdxs = []int32{
	2, // 0: typ_query.Query.keyword:type_name -> typ_query.Keyword
	1, // 1: typ_query.Query.queries:type_name -> typ_query.Queries
	3, // 2: typ_query.Query.levels:type_name -> typ_query.Leveler
	0, // 3: typ_query.Queries.queries:type_name -> typ_query.Query
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_typ_query_query_proto_init() }
func file_typ_query_query_proto_init() {
	if File_typ_query_query_proto != nil {
		return
	}
	file_typ_query_leveler_proto_init()
	file_typ_query_keyword_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_typ_query_query_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Query); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_typ_query_query_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Queries); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_typ_query_query_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Query_Keyword)(nil),
		(*Query_Queries)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_typ_query_query_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_typ_query_query_proto_goTypes,
		DependencyIndexes: file_typ_query_query_proto_depIdxs,
		MessageInfos:      file_typ_query_query_proto_msgTypes,
	}.Build()
	File_typ_query_query_proto = out.File
	file_typ_query_query_proto_rawDesc = nil
	file_typ_query_query_proto_goTypes = nil
	file_typ_query_query_proto_depIdxs = nil
}
