# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: typ_query/keyword.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from typ_query import kv_pb2 as typ__query_dot_kv__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17typ_query/keyword.proto\x12\ttyp_query\x1a\x12typ_query/kv.proto\"[\n\x07Keyword\x12\x1b\n\x02kv\x18\x01 \x01(\x0b\x32\r.typ_query.KvH\x00\x12\'\n\x08keywords\x18\x02 \x01(\x0b\x32\x13.typ_query.KeywordsH\x00\x42\n\n\x08value_of\"A\n\x08Keywords\x12\x0f\n\x07operant\x18\x01 \x01(\t\x12$\n\x08keywords\x18\x02 \x03(\x0b\x32\x12.typ_query.KeywordB4Z2gitlab.com/mippo.app/typ-query.git/go/pb/typ_queryb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'typ_query.keyword_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z2gitlab.com/mippo.app/typ-query.git/go/pb/typ_query'
  _globals['_KEYWORD']._serialized_start=58
  _globals['_KEYWORD']._serialized_end=149
  _globals['_KEYWORDS']._serialized_start=151
  _globals['_KEYWORDS']._serialized_end=216
# @@protoc_insertion_point(module_scope)
