# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: typ_query/keyword.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from typ_query import kv_pb2 as typ__query_dot_kv__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17typ_query/keyword.proto\x12\ttyp_query\x1a\x12typ_query/kv.proto\"i\n\x07Keyword\x12\x1f\n\x02kv\x18\x01 \x01(\x0b\x32\r.typ_query.KvH\x00R\x02kv\x12\x31\n\x08keywords\x18\x02 \x01(\x0b\x32\x13.typ_query.KeywordsH\x00R\x08keywordsB\n\n\x08value_of\"T\n\x08Keywords\x12\x18\n\x07operant\x18\x01 \x01(\tR\x07operant\x12.\n\x08keywords\x18\x02 \x03(\x0b\x32\x12.typ_query.KeywordR\x08keywordsB4Z2gitlab.com/mippo.app/typ-query.git/go/pb/typ_queryb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'typ_query.keyword_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z2gitlab.com/mippo.app/typ-query.git/go/pb/typ_query'
  _globals['_KEYWORD']._serialized_start=58
  _globals['_KEYWORD']._serialized_end=163
  _globals['_KEYWORDS']._serialized_start=165
  _globals['_KEYWORDS']._serialized_end=249
# @@protoc_insertion_point(module_scope)
