# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: typ_query/leveler.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from typ_query import keyword_pb2 as typ__query_dot_keyword__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17typ_query/leveler.proto\x12\ttyp_query\x1a\x17typ_query/keyword.proto\"\x88\x01\n\x07Leveler\x12\x36\n\nkeywordMap\x18\x02 \x03(\x0b\x32\".typ_query.Leveler.KeywordMapEntry\x1a\x45\n\x0fKeywordMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12!\n\x05value\x18\x02 \x01(\x0b\x32\x12.typ_query.Keyword:\x02\x38\x01\x42\x34Z2gitlab.com/mippo.app/typ-query.git/go/pb/typ_queryb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'typ_query.leveler_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z2gitlab.com/mippo.app/typ-query.git/go/pb/typ_query'
  _globals['_LEVELER_KEYWORDMAPENTRY']._loaded_options = None
  _globals['_LEVELER_KEYWORDMAPENTRY']._serialized_options = b'8\001'
  _globals['_LEVELER']._serialized_start=64
  _globals['_LEVELER']._serialized_end=200
  _globals['_LEVELER_KEYWORDMAPENTRY']._serialized_start=131
  _globals['_LEVELER_KEYWORDMAPENTRY']._serialized_end=200
# @@protoc_insertion_point(module_scope)
