# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: typ_query/query.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from typ_query import leveler_pb2 as typ__query_dot_leveler__pb2
from typ_query import keyword_pb2 as typ__query_dot_keyword__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15typ_query/query.proto\x12\ttyp_query\x1a\x17typ_query/leveler.proto\x1a\x17typ_query/keyword.proto\"\xaf\x01\n\x05Query\x12\x13\n\x0bsearch_type\x18\x01 \x01(\t\x12\x13\n\x0btarget_type\x18\x02 \x01(\t\x12%\n\x07keyword\x18\x03 \x01(\x0b\x32\x12.typ_query.KeywordH\x00\x12%\n\x07queries\x18\x04 \x01(\x0b\x32\x12.typ_query.QueriesH\x00\x12\"\n\x06levels\x18\x05 \x03(\x0b\x32\x12.typ_query.LevelerB\n\n\x08value_of\"=\n\x07Queries\x12\x0f\n\x07operant\x18\x01 \x01(\t\x12!\n\x07queries\x18\x02 \x03(\x0b\x32\x10.typ_query.QueryB4Z2gitlab.com/mippo.app/typ-query.git/go/pb/typ_queryb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'typ_query.query_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z2gitlab.com/mippo.app/typ-query.git/go/pb/typ_query'
  _globals['_QUERY']._serialized_start=87
  _globals['_QUERY']._serialized_end=262
  _globals['_QUERIES']._serialized_start=264
  _globals['_QUERIES']._serialized_end=325
# @@protoc_insertion_point(module_scope)
